### ISSUE TITLE
easywebpack-vue 中的loader.js配置中关于/\.vue$/ 设置了 exclude：/node_modules/ 导致无法解析vue-ui组件库

### ISSUE THREAD

**Issue by smallos** [easy-team/easywebpack-vue#7]
目前这个问题有什么好的方式避免吗？
我目前的做法是删除：exclude：/node_modules/

**Comment by hubcarl** [comment]
see https://www.yuque.com/easy-team/easywebpack/problem

**Comment by smallos** [comment]
> see https://www.yuque.com/easy-team/easywebpack/problem
> 
> [webpack/webpack#2031](https://github.com/webpack/webpack/issues/2031)

include: [/app\/web/, /node_modules\/lefit/]   
lefit 下面是我的组件所在项目，不过提示依旧。
exclude: [] 的设置是生效的，这有遇到过吗？

![image](https://user-images.githubusercontent.com/12025733/53318681-0d2d3200-390b-11e9-85c8-c195c41407f7.png)

--------

问题2：
服务端渲染是，import的问题，babel 设置了exclude: [] 还是会有问题。
`
2019-02-25 14:43:13,304 ERROR 30547 [land/class/index.js] server render bundle error, try client render, the server render error /Users/Niok/Documents/LeFit/LeFront/fit-spoon/node_modules/lefit/src/components/button/index.js:1
(function (exports, require, module, __filename, __dirname) { import LeButton from './src/button.vue';
                                                                     ^^^^^^^^
SyntaxError: Unexpected identifier
`

**Comment by hubcarl** [comment]
@smallos  请提供一个可重现的 demo ，可以放到GitHub上

**Comment by smallos** [comment]
好的，
https://github.com/smallos/vue-ssr-demo   
用的最基础基础模版，初始化就遇到类似的问题。目前还没有修改代码
![image](https://user-images.githubusercontent.com/12025733/53414970-f3731400-3a0a-11e9-9b33-40cdd4749081.png)

**Comment by hubcarl** [comment]
@smallos 先 npm cache clean --force 重新按照依赖试试 或者 用  yarn install 安装试试。原因是
webpack 新的一个版本导致的动态 import 的问题
